### ISSUE TITLE
Missing clusterrole prometheus-k8s permissions

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/observability#186]
### Bug description

Without the next permissions we cannot [node-problem-detector](https://github.com/gitpod-io/ops/blob/main/deploy/workspace/manifests/node-problem-detector.yaml) or [kubelet-stats-exporter](https://github.com/gitpod-io/ops/blob/main/deploy/workspace/manifests/kubelet-stats-exporter.yaml)

```
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints
  verbs:
  - get
```

What's the procedure to add this permissions?

### Steps to reproduce

-
